name: strefa_ciszy
description: "Stock control app for small entertainment a/v company."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# change build '+'
# and in xcode
version: 1.0.0+40

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  http: ^1.4.0

  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.7
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  excel: ^4.0.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  cross_file: ^0.3.5+1
  url_launcher: ^6.3.1
  flutter_email_sender: ^7.0.0
  syncfusion_flutter_xlsio: ^29.2.10
  open_file: ^3.5.10
  firebase_app_check: ^0.3.2+10
  csv: ^6.0.0
  qr_flutter: ^4.1.0
  flutter_image_compress: ^2.4.0
  google_maps_flutter: ^2.12.3
  google_maps_flutter_web: ^0.5.12+2
  path: ^1.9.1
  auto_size_text: ^3.0.0
  file_picker: ^10.2.0
  package_info_plus: ^8.3.0
  rxdart: ^0.28.0
  dio: ^5.9.0
  web: ^1.1.1
  collection: ^1.19.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flutter_dropzone: ^4.2.1
  desktop_drop: ^0.7.0
  image: ^4.3.0
  photo_view: ^0.15.0
  firebase_messaging: ^15.2.10
  receive_sharing_intent: ^1.8.1

dependency_overrides:
  isar_flutter_libs:
    path: third_party/isar_flutter_libs

dev_dependencies:
  build_runner: ^2.4.13 
  isar_generator: ^3.1.0+1
  analyzer: ^5.13.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/apple_ios_logo.png
    - assets/images/android_logo.png
    - assets/images/strefa_ciszy_logo.png
    - assets/images/strefa_S.png
    - assets/favicon/Icon-512.png
    - assets/images/Lee_logo_app_dev.png
    - assets/images/dev_logo.png
    - assets/images/dev_logo_BOLD.png
    - assets/images/dev_logo_DARK.png
    - assets/images/dev_logo_HOLLOW.png
    - assets/images/dev_logo_LIGHT.png
    - assets/images/dev_logo_PILL.png
    - version.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
